import type { ReactNode } from "react";

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function PrivacyLayout({ children }: { children: ReactNode }) {
  return (
    <div className="privacy-layout-wrapper">
      {children}
    </div>
  );
}

