import "./globals.css";
import Toolbar from './components/Toolbar';
import Script from "next/script";

export const metadata = {
  title: "Coco Calgary",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
      <html lang="en">
          <head>
              <link
                  href="https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;600&display=swap"
                  rel="stylesheet"
              />
          </head>
          <body className="bg-white">
              {/*  Google Tag Manager (gtag.js) */}
              <Script
                  strategy="afterInteractive"
                  src="https://www.googletagmanager.com/gtag/js?id=G-3S12T44MMW"
              />
              <Script
                  id="google-analytics"
                  strategy="afterInteractive"
                  dangerouslySetInnerHTML={{
                      __html: `
                          window.dataLayer = window.dataLayer || [];
                          function gtag(){dataLayer.push(arguments);}
                          gtag('js', new Date());
                          gtag('config', 'G-3S12T44MMW');
                      `,
                  }}
              />

              {/*  Microsoft Clarity Tracking Code */}
              <Script
                  id="microsoft-clarity"
                  strategy="afterInteractive"
                  dangerouslySetInnerHTML={{
                      __html: `
                          (function(c,l,a,r,i,t,y){
                              c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                              t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
                              y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
                          })(window, document, "clarity", "script", "q3ynfe4cyj");
                      `,
                  }}
              />

              <Toolbar />
              <main>{children}</main>
          </body>
      </html>
  );
}
